services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - '1025:1025' #smtp
      - '8025:8025' #WEB UI

  postgres:
    image: postgres:16-alpine
    container_name: postgres_serviceMaintence
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: serviceMaintence
    ports:
      - '5432:5432'
